name = "colbin-test-api"
main = "src/index.ts"

## node js compatibility flags
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
compatibility_date = "2024-09-23"

## ENVs 
[vars]
AUTH_SECRET = "AmQZv2lCd3GpNEZzGX3Bv7iUJpeEwmqz"

## neon connection string
NEON_URI = "postgresql://neondb_owner:npg_F6PJgUuQMxo4@ep-green-moon-admrs56r-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
